### ISSUE TITLE
Godot Rig

### ISSUE THREAD

**Issue by DinkleBird** [deeps-meen/S-S#2]
Rig is showing double bones

**Comment by DinkleBird** [comment]
I started working on determining why two rigs are showing.
May have to recreate rig but I'll keep troubleshooting

**Comment by deeps-meen** [comment]
I think it's an export issue. First delete all unused skeletons or extra bones. but do no save the changes. Then try to export it (.glb). Undo the changes after export that way you can have clean export without affecting the blender file.
